name = "hono-short-url"
compatibility_date = "2024-09-26"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
#  { binding = "URL_MAPPINGS", id = "your-kv-namespace-id" }
]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"